# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f79e45678381f6e3f7cefa42b757e50acee827ce570bd7efac49f5cdc26c36db82e6b21c9d3eaf9523368a41c43969b3b8ba2436279067cd3e32b070a1abbde

test:
  secret_key_base: 4ba9d0c8019ad21473158109a83eb5236778c36c45a3ee8299fee80590bece076328fa6e7004a6502198bf098492e962dea0f33407c79b5391ebee6eee5ca1da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
